#!/usr/bin/env bash
#
# A Vim plugin manager designed to work with vim-pathogen.
#
# The workflow is:
#
# 1. Update `plugins` by hand.
# 2. Run this script.
#
# This is one step too many: I should roll (1) into (2).
#
#
# SYNOPSIS
#
#   voom
#   voom <update> [name]
#
#
# OPTIONS
#
#   update [name]
#       Updates any plugins which aren't up to date.  If `name` is given, update
#       only the named plugin.
#


set -e

VIM_DIR=~/dotvim
REPOS="$VIM_DIR/plugins"
SOURCES_DIR="$VIM_DIR/src"
BUNDLE_DIR="$VIM_DIR/bundle"
COMMENT='^#'
action="$1"


test -f "$REPOS" || {
  echo >&2 "Could not locate '$REPOS'."
  exit 1
}

is_remote_repo() {
  local slashes="${1//[^\/]}"
  local count="${#slashes}"
  [ "$count" -eq 1 ]
}

install_plugin() {
  local line="$1"
  ([ -z "$line" ] || [[ "$line" =~ $COMMENT ]]) && continue

  local plugin_name=${line##*/}

  [ -L "$BUNDLE_DIR/$plugin_name" ] || {
    if is_remote_repo "$line"; then
      [ -d "$SOURCES_DIR/$plugin_name" ] || git clone --depth 1 "https://github.com/$line.git" "$SOURCES_DIR/$plugin_name" >/dev/null 2>&1
      ln -nfs "$SOURCES_DIR/$plugin_name" "$BUNDLE_DIR/$plugin_name"
    else
      ln -nfs "$line" "$BUNDLE_DIR/$plugin_name"
    fi
    echo "installed $plugin_name"
  }
}

uninstall_plugin() {
  local dir="$1"
  plugin_name=${dir##*/}
  (grep -v "$COMMENT" $REPOS | grep -q $plugin_name -) || {
    rm "$dir"
    [ -d "$SOURCES_DIR/$plugin_name" ] && rm -rf "$SOURCES_DIR/$plugin_name"
    echo "uninstalled $plugin_name"
  }
}


install_missing_plugins() {
  [ -d "$SOURCES_DIR" ] || mkdir "$SOURCES_DIR"

  while read line
  do
    install_plugin "$line" &
  done < "$REPOS"
  wait
}

uninstall_unwanted_plugins() {
  for dir in $BUNDLE_DIR/*; do
    uninstall_plugin "$dir"
  done
}

case $action in
'')
  install_missing_plugins
  uninstall_unwanted_plugins
  ;;

update)
  for dir in $SOURCES_DIR/*; do
    cd $dir
    plugin_name=${dir##*/}

    [ -n "$2" ] && [ "$2" != $plugin_name ] && continue

    upstream=$(git ls-remote --heads origin master | awk {'print $1'})
    installed=$(git rev-parse master)
    [ "$upstream" == "$installed" ] || {
      git pull -q
      echo "updated $plugin_name:"
      git log --pretty=format:"    %h %s" $installed..$upstream
    }
  done
  ;;

help | --help | -h)
  echo "Usage: $(basename $0) <update> [name]"
  ;;

*)
  echo >&2 "Usage: $(basename $0) <update> [name]"
  exit 1
  ;;
esac

